language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# install build dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq python-scipy python-sympy python-pyparsing
# command to install dependencies
install:
  # install different versions of numpy for python 2 and 3
  - "if [ ${TRAVIS_PYTHON_VERSION:0:1} == '2' ]; then pip install numpy==1.6.2 --use-mirrors; else pip install numpy --use-mirrors; fi"
  - "pip install scipy sympy sphinx ipython --use-mirrors"
  # install different pyparsing versions for python 2 and 3
  - "if [ ${TRAVIS_PYTHON_VERSION:0:1} == '2' ]; then pip install pyparsing==1.5.7 --use-mirrors; else pip install pyparsing --use-mirrors; fi"
  - "pip install . --use-mirrors"
# command to run tests (make sure to not run it from the source directory)
script: "cd ~;nosetests --with-doctest brian2"
notifications:
  email: false
