# Frozen environment of Brian dependencies, used in the RTD build
name: brian2_docs
channels:
- conda-forge
- defaults
dependencies:
- alabaster=0.7.10=py_0
- asn1crypto=0.22.0=py27_0
- babel=2.4.0=py27_0
- blas=1.1=openblas
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py27_0
- cffi=1.10.0=py27_0
- chardet=3.0.4=py27_0
- cryptography=2.0.3=py27_0
- cython=0.26.1=py27_0
- docutils=0.14=py27_0
- enum34=1.1.6=py27_1
- fastcache=1.0.2=py27_0
- gmp=6.1.2=0
- gmpy2=2.0.8=py27_1
- idna=2.5=py27_0
- imagesize=0.7.1=py27_0
- ipaddress=1.0.18=py27_0
- jinja2=2.9.6=py27_0
- libffi=3.2.1=3
- markupsafe=1.0=py27_0
- mpc=1.0.3=4
- mpfr=3.1.5=0
- mpmath=0.19=py27_2
- ncurses=5.9=10
- numpy=1.13.1=py27_blas_openblas_200
- openblas=0.2.19=2
- openssl=1.0.2l=0
- pip=9.0.1=py27_0
- py-cpuinfo=3.3.0=py27_0
- pycparser=2.18=py27_0
- pygments=2.2.0=py27_0
- pyopenssl=17.2.0=py27_0
- pyparsing=2.2.0=py27_0
- pysocks=1.6.7=py27_0
- python=2.7.13=1
- pytz=2017.2=py27_0
- readline=6.2=0
- requests=2.18.4=py27_1
- scipy=0.19.1=py27_blas_openblas_202
- setuptools=36.3.0=py27_0
- six=1.10.0=py27_1
- snowballstemmer=1.2.1=py27_0
- sphinx=1.6.3=py27_0
- sphinx_rtd_theme=0.2.4=py27_0
- sphinxcontrib-websupport=1.0.1=py27_0
- sqlite=3.13.0=1
- sympy=1.1.1=py27_0
- tk=8.5.19=2
- typing=3.6.2=py27_0
- urllib3=1.22=py27_0
- weave=0.15.0=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.11=0
- bsddb=1.0=py27_1
- db=5.3.28=1
- libgfortran=3.0.0=1
- pip:
  - sphinx-rtd-theme==0.2.4
  - stencila==0.27.0
  - werkzeug==0.12.2
